import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import ConvexClerkProvider from "@/providers/ConvexClerkProvider";
// --- IMPORT SONNER ---
import { Toaster } from "@/components/ui/sonner"; // Assuming you installed it to 'ui'
import { Sidebar } from "@/components/ui/sidebar-new";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClerkProvider>
          <SidebarProvider>

            <Sidebar>
          <div className="flex"></div>
            {/* --- 1. This flex container holds the sidebar and main content --- */}
            <div className="flex">
              <AppSidebar />

              {/* --- 2. This wrapper holds the Navbar + Content --- */}
              <div className="flex-1 flex flex-col h-screen">
                {/* --- 3. Navbar is at the top of this wrapper --- */}
               

                {/* --- 4. Main content area scrolls independently --- */}
                <main className="p-6 overflow-auto">
                  
                  {children}
                </main>
              </div>
            </div>
            <Toaster richColors />

             </Sidebar>
          </SidebarProvider>
        </ConvexClerkProvider>

        
      </body>
    </html>
  );
}
